apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.useCluster }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: {{ .Values.rbac.roleName }}
  {{- if .Values.rbac.useCluster }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
{{- if .Values.rbac.useCluster }}
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
{{- end }}
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
  verbs:
    - "*"
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get