apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.useCluster }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ .Values.rbac.roleBindingName }}
  {{- if not .Values.rbac.useCluster }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.useCluster }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ .Values.rbac.roleName }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}