image: ghcr.io/joengjyu/etcd-operator-controller:4a2b3f6
rbac:
  useCluster: true
  roleName: etcd-operator-role
  roleBindingName: etcd-operator-rolebinding
karmada:
  enabled: true
  clusterName: member1