apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-cluster-operator
  template:
    metadata:
      labels:
        app: etcd-cluster-operator
    spec:
      containers:
      - name: etcd-cluster-operator
        image: {{ .Values.image }}
        command:
        - etcd-operator
        # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name