apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-restore-operator
  labels:
    name: etcd-restore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-restore-operator
  template:
    metadata:
      labels:
        app: etcd-restore-operator
    spec:
      containers:
      - name: etcd-restore-operator
        image: {{ .Values.image }}
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
